import { Inter } from "next/font/google";
// import "./globals.css";
import Script from "next/script";
import Navbar from "@components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gracieux Moda",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://www.instagram.com/embed.js"
          strategy="lazyOnload"
        />
      </head>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
